### ISSUE TITLE
Pdf icon not rendered in header with `download_link: header` option

### ISSUE THREAD

**Issue by nihalshah-dev** [domWalters/mkdocs-to-pdf#66]
Hi again! 👩‍💻

Found a minor bug 🐛

## Description
The plugin is configured correctly, and the `download_link: header` option is enabled. However, the PDF icon is either not rendered in the header as expected or even it is rendered , it appears in other parts of the documentation (e.g., at the top of each page). 

The plugin's `inject_link` function in `pdf_event_hook.py` seem to be configured correctly, but the behavior does not align with the expected default functionality.

**pdf_event_hook.py -** 

```python
import logging
import os.path
import subprocess
from bs4 import BeautifulSoup
from mkdocs.structure.pages import Page
from mkdocs import plugins

def pre_pdf_render(soup: BeautifulSoup, logger: logging) -> BeautifulSoup:
    def fix_img_src(img_src):
        FILE_PREFIX = 'file://'

        if img_src[:7] != FILE_PREFIX:
            return img_src

        if os.path.exists(img_src[7:]):
            return img_src

        img_src = img_src[7:]
        img_arr = img_src.split('/')

        if img_arr[-2] != img_arr[-3]:
            logger.warning('pre_pdf_render: broken image path found at ' + img_src)
            return FILE_PREFIX + img_src

        del img_arr[-2]
        img_src_new = '/'.join(img_arr)

        if os.path.exists(img_src_new):
            # bug was identified and fixed
            return FILE_PREFIX + img_src_new
        else:
            return FILE_PREFIX + img_src

    logger.info('(hook on pre_pdf_render)')

    for img in soup.find_all('img', src=True):
        img['src'] = fix_img_src(img['src'])

    return soup

def inject_link(html: str, href: str,
                page: Page, logger: logging) -> str:
    """Adding PDF View button on navigation bar"""

    def _pdf_icon():
        _ICON = '''
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
<path d="M128,0c-17.6,0-32,14.4-32,32v448c0,17.6,14.4,32,32,32h320c17.6,0,32-14.4,32-32V128L352,0H128z" fill="#E2E5E7"/>
<path d="m384 128h96l-128-128v96c0 17.6 14.4 32 32 32z" fill="#B0B7BD"/>
<polygon points="480 224 384 128 480 128" fill="#CAD1D8"/>
<path d="M416,416c0,8.8-7.2,16-16,16H48c-8.8,0-16-7.2-16-16V256c0-8.8,7.2-16,16-16h352c8.8,0,16,7.2,16,16  V416z" fill="#009688"/>
<g fill="#fff">
<path d="m101.74 303.15c0-4.224 3.328-8.832 8.688-8.832h29.552c16.64 0 31.616 11.136 31.616 32.48 0 20.224-14.976 31.488-31.616 31.488h-21.36v16.896c0 5.632-3.584 8.816-8.192 8.816-4.224 0-8.688-3.184-8.688-8.816v-72.032zm16.88 7.28v31.872h21.36c8.576 0 15.36-7.568 15.36-15.504 0-8.944-6.784-16.368-15.36-16.368h-21.36z"/>
<path d="m196.66 384c-4.224 0-8.832-2.304-8.832-7.92v-72.672c0-4.592 4.608-7.936 8.832-7.936h29.296c58.464 0 57.184 88.528 1.152 88.528h-30.448zm8.064-72.912v57.312h21.232c34.544 0 36.08-57.312 0-57.312h-21.232z"/>
<path d="m303.87 312.11v20.336h32.624c4.608 0 9.216 4.608 9.216 9.072 0 4.224-4.608 7.68-9.216 7.68h-32.624v26.864c0 4.48-3.184 7.92-7.664 7.92-5.632 0-9.072-3.44-9.072-7.92v-72.672c0-4.592 3.456-7.936 9.072-7.936h44.912c5.632 0 8.96 3.344 8.96 7.936 0 4.096-3.328 8.704-8.96 8.704h-37.248v0.016z"/>
</g>
<path d="m400 432h-304v16h304c8.8 0 16-7.2 16-16v-16c0 8.8-7.2 16-16 16z" fill="#CAD1D8"/>
</svg>
'''
        return BeautifulSoup(_ICON, 'html.parser')

    logger.info(f'(hook on inject_link: {page.title})')
    soup = BeautifulSoup(html, 'html.parser')

    article = soup.find(class_='md-header-nav')
    if not article:
        article = soup.find(class_='md-header__inner')

    if article:
        a = soup.new_tag('a', href=href, title='download PDF',
                         **{'class': 'md-header__button md-header-nav__button md-icon'})
        a.append(_pdf_icon())
        article.append(a)
        return str(soup)

    return html
```

**mkdocs.yml -** 

```yaml
plugins:
  to-pdf:
    enabled_if_env: ENABLE_PDF_EXPORT
    verbose: true
    toc_level: 3
    back_cover: true
    output_path: !ENV [PDF_OUTPUT_PATH]
    custom_template_path: 'pdf-templates'
    download_link: header
```

## Questions?? 

1) Are there additional configuration options or requirements for the `pdf_event_hook` to work correctly with custom templates or without custom templates?
2) Is there a fallback mechanism or default behavior for the inject_link function when the targeted header classes (md-header-nav or md-header__inner) are not found?
3) I tried removing the `inject_link` function completely , hoping this is already handled by the plugin [here ](https://github.com/domWalters/mkdocs-to-pdf/blob/b354a24569b9549582065fc65b3dc09db01bd892/src/mkdocs_to_pdf/drivers/event_hook.py#L49)and that is why `download_link` option was introduced. unfortunately throws error - 

![Image](https://github.com/user-attachments/assets/73b0d1fd-d4ce-4fd0-91c7-f83dae0951bb)

4) Can you provide guidance or documentation for users who need to customize the pdf_event_hook for specific use cases?
5) What do you mean by Stuff to Migrate here? - https://mkdocs-to-pdf.readthedocs.io/en/latest/stuff-to-migrate/#advanced-rendering-hooks-experimental.  Is the rendering hooks feature not a part of the latest release?

I expect more detailing on `download_link: header or footer` option.

Thanks! ✌

let me know if you need any more inputs from my side.

**Comment by hkato** [comment]
I tried the following for now, and it seems to be working.
I don't have time now, so I'll take a look at it this weekend. If you have any information on plugins, themes and custom template, please let me know.

Create a simple/minimal MkDocs project

```sh
uv init
uv add mkdocs-material mkdocs-to-pdf qrcode
uv run mkdocs new .
```

Add your `mkdocs.yml` configuration

```yaml
site_name: My Docs

theme:
  name: material

plugins: 
  - search
  - to-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      verbose: true
      toc_level: 3
      back_cover: true
      output_path: !ENV [PDF_OUTPUT_PATH]
      custom_template_path: 'pdf-templates'
      download_link: header
```

Put your `pdf_event_hook.py`

Run the MkDocs server

```sh
ENABLE_PDF_EXPORT=1 PDF_OUTPUT_PATH=foo.pdf uv run mkdocs serve
```

**Comment by Thiti517** [comment]
⚠  **This response is based solely on my reading and understanding of the code and documentation. I haven't had time to test it yet. I’ll try to confirm this theory over the weekend if I find time.**

---

## Why does the fallback function crash ?

> 3. I tried removing the inject_link function completely , hoping this is already handled by the plugin [here ](https://github.com/domWalters/mkdocs-to-pdf/blob/b354a24569b9549582065fc65b3dc09db01bd892/src/mkdocs_to_pdf/drivers/event_hook.py#L49)and that is why download_link option was introduced. unfortunately throws error -
> 
> ![image](https://private-user-images.githubusercontent.com/54808653/431739401-73b0d1fd-d4ce-4fd0-91c7-f83dae0951bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQzNTkyOTgsIm5iZiI6MTc0NDM1ODk5OCwicGF0aCI6Ii81NDgwODY1My80MzE3Mzk0MDEtNzNiMGQxZmQtZDRjZS00ZmQwLTkxYzctZjgzZGFlMDk1MWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDExVDA4MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmN2IyYzAzNTFjNmE4NmYzOTAyZmUzMjZhMjFkN2U0YTg1ZDVmNWExZDhlNjg2MzgxZjI4MWEwZjM0ZWFkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wezyxEfY306kTEojhvXK9BPYtajxR-e-M5aR0L0a5Cs)

What theme are you using? If it's neither `mkdocs` (default) nor `material`, the error might be due to a recent change in the default behavior of `inject_link`.

When no custom `inject_link` is provided in `pdf_event_hook.py`, it falls back to the function in the corresponding `theme_handler`. There are three handlers available:

- `material`
- `mkdocs`
- `generic`

To determine which handler to use, [`generator.py`](https://github.com/domWalters/mkdocs-to-pdf/blob/b354a24569b9549582065fc65b3dc09db01bd892/src/mkdocs_to_pdf/generator.py#L296) does the following:

```
def _load_theme_handler(self):
        theme = self._options.theme_name
        custom_handler_path = self._options.theme_handler_path
        module_name = '.' + (theme or 'generic').replace('-', '_')
```

If your theme is not `mkdocs` or `material` it will use `generic`.

Now, the [`generic.py`](https://github.com/domWalters/mkdocs-to-pdf/blob/b354a24569b9549582065fc65b3dc09db01bd892/src/mkdocs_to_pdf/themes/generic.py#L12) implementation only `inject_link` function with *2 arguments not 5*:

```py
def inject_link(html: str, href: str) -> str:
```

This is a problem, as the fallback mechanism expects an `inject_link` function with 5 arguments, like in the other theme handlers. That is likely causing the error you're seeing.

### Note for the devs

> **The fallback mechanism calls the `inject_link` function from the selected `theme_handler` with 5 arguments. Therefore, all `theme_handler` implementations should define `inject_link` with 5 parameters.**

## `download_link` option

It is important to note that this option is only available for material theme since only material `theme_handler` implement a behavior for this option.

## Documentation and meaning of '*Stuff to Migrate*'

Until confirmed by the devs, my guess is that since the `pdf_event_hook.py` feature was marked as **experimental** on the forked project [`mkdocs-with-pdf`](https://github.com/orzih/mkdocs-with-pdf?tab=readme-ov-file#advanced-rendering-hooks-experimental), i would assume that it is still the case here and that it's use is still being worked on and then not completly available.

In short:

- The '*"Download the PDF" button*' feature and it's options `download_link` should only be used with intended theme (`material`)
- Avoid using custom `pdf_event_hook.py` for now.

Hope it helped a little :D

**Comment by Thiti517** [comment]
With a list of the plugins and the theme configuration, I should be able to help figure out an `inject_link` function that would work, if you'd like.

(Remember that `pdf_event_hook.py` is still experimental and that the solution i would provide might not work from a version to another of this plugin)

I also wanted to note that in my previous response, I assumed your theme isn't `material`, since that's the only logical explanation for the "*`inject_link` with 2 arguments instead of 5*" error you're experiencing. However, it could be something else that's causing `generator.py` to select the `generic` theme handler, even if you are using `material`.

**Comment by nihalshah-dev** [comment]
> With a list of the plugins and the theme configuration, I should be able to help figure out an `inject_link` function that would work, if you'd like.
> 
> (Remember that `pdf_event_hook.py` is still experimental and that the solution i would provide might not work from a version to another of this plugin)
> 
> I also wanted to note that in my previous response, I assumed your theme isn't `material`, since that's the only logical explanation for the "_`inject_link` with 2 arguments instead of 5_" error you're experiencing. However, it could be something else that's causing `generator.py` to select the `generic` theme handler, even if you are using `material`.

Thanks for all the research👨‍💻.

Here are my config details - 

```yaml
[mkdocs](https://pypi.org/project/mkdocs/)==1.6.1
[mkdocs-material](https://pypi.org/project/mkdocs-material/)==9.6.8
```

plugins - 

```
dependencies = [
  "mkdocs == 1.6.1",
  "mike == 2.1.3",
  "mkdocs-macros-plugin == 1.3.7",
  "markdown-include == 0.8.1",
  "markdown-katex == 202406.1035",
  "plantuml-markdown == 3.11.1",
  "pygments == 2.19.1",
  "certifi == 2025.1.31",
  "pymdown-extensions == 10.14.3",
  "pangocffi == 0.13.0",
  "weasyprint<=65.0",
  "mkdocs-exclude == 1.0.2",
  "mkdocs-redirects == 1.2.2",
  "mkdocs-same-dir == 0.1.3",
  "mkdocs-include == 1.0.0",
  "mkdocs-multirepo-plugin == 0.8.3",
  "mkdocs-include-markdown-plugin == 7.1.5",
  "yamllint ==1.37.0",
  "mkdocs-code-validator == 0.2.0",
  "mkdocs-enumerate-headings-plugin == 0.6.2",
  "mkdocs-render-swagger-plugin == 0.1.2",
  "mkdocs-awesome-pages-plugin == 2.10.1",
  "mkdocs-placeholder-plugin == 0.5.1",
  "mkdoxy == 1.2.7",
  "mkdocs-caption == 1.3.0",
  "neoteroi-mkdocs == 1.1.0",
  "mkdocs-material-extensions == 1.3.1",
  "mkdocs-glightbox == 0.4.0",
  "mkdocstrings-python ==1.16.8",
  "qrcode == 8.0",
  "beautifulsoup4<=4.13.3",
  "mkdocs-to-pdf>=0.10.0",
]
```

**Comment by Thiti517** [comment]
> With a list of the plugins and the theme configuration...

I was more talking about `mkdocs.yml` `plugins` and `theme` section

**Comment by hkato** [comment]
@Thiti517 

Sorry, I made this change.
I had checked the material, mkdocs, and readthedocs themes, but I hadn't checked the other third-party themes.

I added `mkdocs-bootswatch` and switched to a different theme, and then it reproduced.

```python
TypeError: inject_link() takes 2 positional arguments but 5 were given
```

> - The '"Download the PDF" button' feature and it's options download_link should only be used with intended theme (material)

Yes.

@nihalshah-dev 

>I was more talking about mkdocs.yml: plugins and theme sections

It seems you are using a theme that is not material, mkdocs, or readthedocs.

@Thiti517 

Anyway, sorry for the trouble. I'll fix it.
First, I'll revert and make it function only when the material theme is used.

**Comment by Thiti517** [comment]
> Sorry, I made this change. I had checked the material, mkdocs, and readthedocs themes, but I hadn't checked the other third-party themes.
> 
> I added `mkdocs-bootswatch` and switched to a different theme, and then it reproduced.
> 
> TypeError: inject_link() takes 2 positional arguments but 5 were given

You could easily fix this by making [`generic.py inject_link`](https://github.com/domWalters/mkdocs-to-pdf/blob/b354a24569b9549582065fc65b3dc09db01bd892/src/mkdocs_to_pdf/themes/generic.py#L12) function take the 5 arguements instead of 2.

this:

```py
def inject_link(html: str, href: str) -> str:
```

become:

```py
def inject_link(html: str, href: str,
                page: Page, logger: logging, options: Options) -> str:
```

This would fix the error. Even if `generic.py` don't make use of the 3 added arguments.

**Comment by hkato** [comment]
@Thiti517 

I just changed #67 ... Should I have changed `generic.py`?

But it seems like @domWalters  is busy.

**Comment by nihalshah-dev** [comment]
> It seems you are using a theme that is not material, mkdocs, or readthedocs.

I use a custom theme inherited from `material `theme

**Comment by nihalshah-dev** [comment]
> I'm not sure what the difference is with the Material theme. However, since your theme is processed using `generic.py`, the `download_link` option is not available.
> uv add git+https://github.com/domWalters/mkdocs-to-pdf.git@fix-66-download-link-with-event-hook
> This fix does not contain [#64](https://github.com/domWalters/mkdocs-to-pdf/issues/64) ...
> 
> I tested [#67](https://github.com/domWalters/mkdocs-to-pdf/pull/67) with [MkDocs Bootstrap Theme](https://mkdocs.github.io/mkdocs-bootswatch/) and there were no errors. Of course, there isn't a download link. 

@hkato I would prefer to test when merged to `develop` branch with #64 


> And could you please use your `pdf_event_hook.py`?

when `pdf_event_hook.py` - 

![Image](https://github.com/user-attachments/assets/db8a733f-ac46-415e-99b5-92f81571c10c)

and not - 

![Image](https://github.com/user-attachments/assets/cb0357fb-8645-447a-bbd7-5ea52a01f521)

**Comment by domWalters** [comment]
@nihalshah-dev I just merged `develop` back onto `fix-66-download-link-with-event-hook`, so it now has the relaxed dependencies fix in it.

Can you try it and see if it resolves this issue?

```toml
[project]
dependencies = [
"mkdocs-to-pdf"
]

[tool.uv.sources]
mkdocs-to-pdf = { git = "https://github.com/domWalters/mkdocs-to-pdf.git", rev = "fix-66-download-link-with-event-hook" }
```

**Comment by hkato** [comment]
This issue includes two problems.

One is 

```python
TypeError: inject_link() takes 2 positional arguments but 5 were given
```

This one will probably be fixed with this.

> I just merged develop back onto fix-66-download-link-with-event-hook, so it now has the relaxed dependencies fix in it.

Another one is related to @nihalshah-dev 's custom theme and custom `pdf_event_hook.py`.

This function is experimental and not supported for custom themes.

@domWalters @nihalshah-dev 
Is my understanding correct?

**Comment by hkato** [comment]
How about this ? @domWalters @Thiti517 
 
- Remove the `download_link` option.
- `meterial` theme
     - Always display the PDF download icon in the navigation header.
     - Remove the footer link feature.
     - Remove the docs and sample code from the "Staff to Migrate" section (this sample code is specifically for the `material` theme to avoid confusion).
     - Users can override this type of feature using `pdf_event_hook.py`
- Other themes
     - To use this type of feature, users need to implement `pdf_event_hook.py`.
- How to customize (docs and sample code)
     - Initially, there is no docs or sample code. It will be updated in the future.
     - Update this issue or create a new documentation issue, and summarize it in the docs.

**Comment by nihalshah-dev** [comment]
> This issue includes two problems.
> 
> One is
> 
> TypeError: inject_link() takes 2 positional arguments but 5 were given
> This one will probably be fixed with this.
> 
> > I just merged develop back onto fix-66-download-link-with-event-hook, so it now has the relaxed dependencies fix in it.
> 
> Another one is related to [@nihalshah-dev](https://github.com/nihalshah-dev) 's custom theme and custom `pdf_event_hook.py`.
> 
> This function is experimental and not supported for custom themes.
> 
> [@domWalters](https://github.com/domWalters) [@nihalshah-dev](https://github.com/nihalshah-dev) Is my understanding correct?

Yes, that's right!

with `develop` branch merge with `fix-66-download-link-with-event-hook` , the positional arguments error is fixed now. Thanks @domWalters @hkato.

**Comment by nihalshah-dev** [comment]
> Indeed, the solution is to align the number of arguments in the `inject_link` function across all theme handlers. Updating the `generic.py` version to accept 5 parameters makes it consistent and compatible.
> ## **3.** Custom theme `inject_link` logic
> Now for [@nihalshah-dev](https://github.com/nihalshah-dev),
> 
> Since your theme is not `material`, the plugin falls back to using `generic.py`'s `inject_link` function. This function only appends a `<link rel="alternate">` tag to the `<head>` of the HTML:
> 
> if soup.head:
>     link = soup.new_tag('link', href=href, rel='alternate',
>                         title='PDF', type='application/pdf')
>     soup.head.append(link)
>     return str(soup)
> The `rel="alternate"` tag informs browsers that an alternate version (e.g., PDF) of the page exists, but modern browsers don’t display this by default.
> 
> According to [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel#alternate):
> 
> > Indicates an alternate representation of the current document. Valid for `<link>`, `<a>`, and `<area>`, the meaning depends on the values of the other attributes.
> 
> **But** since you are using a custom `pdf_event_hook.py` file it will override `generic.py`, that's great !
> 
> > the pdf icon appears on top of the page and not in the header.
> > maybe the positioning is overwritten because of the html class in my inject_link not really sure.
> 
> According to your code you are looking for an `article` element which is where the content of the page, not the `<header>` with it's `<nav>`.
> 
> > article = soup.find(class_='md-content__inner') # This retrieve the page content not the header > nav
> 
> Try to take a look at your site structure to identify the `header > nav` (by it's classes) that should contain the download link.
> 
> For example the structure/classes of this project documentation `<nav>` is:
> 
> <nav class="md-header__inner md-grid">                             
>   <a    class="md-header__button md-logo"></a>                     
>   <label class="md-header__button md-icon"></label>                
>   <div   class="md-header__title md-header__title--active"></div>  
>   <form  class="md-header__option"></form>                         
>   <label class="md-header__button md-icon"></label>                
>   <div   class="md-search"></div>                                  
>   <div   class="md-header__source"></div>                          
>   <a    class="md-header-nav__button md-icon"></a>                 
> </nav>
> Check if it's the same for your theme.
> 
> You should end up with something like this in your `pdf_event_hook.py`:
> 
> def inject_link_header(html: str, href: str,
>                        page: Page, logger: logging) -> str:
>     def _pdf_icon():
>         _ICON = '''...'''  # SVG icon code omitted for brevity
>         return BeautifulSoup(_ICON, 'html.parser')
> 
>     nav = soup.find('nav', class_='YOUR-HEADER-NAV-CLASS')
>     if nav:
>         a = soup.new_tag('a', href=href, title='PDF',
>                          **{'class': 'md-icon md-content__icon md-pdf__icon'})
>         a.append(_pdf_icon())
>         nav.append(a)
>         return str(soup)
> 
>     return html
> ### Note
> If you’re using a custom theme, it’s better to define a dedicated `theme_handler`. This is supported via the undocumented `theme_handler_path` option, which is implemented but not mentioned in the official documentation or the parent project documentation. You can find it in [this part of the code](https://github.com/domWalters/mkdocs-to-pdf/blob/9703343d0b66b53e820f43f4e814fd30428b7f6f/src/mkdocs_to_pdf/generator.py#L296C5-L318C33).
> 
> If your custom theme is very similar to `material`, you could try copying the `material.py` and `material.scss` files and tailor it to your needs
> 
> ⚠ I haven’t yet tested whether this functionality works correctly, rememeber that it was not documented on parent project.
> 
> Hope it helped a little :D

Thanks a lot @Thiti517 for all the detailed research. well now -

- inject_link fix --> fixed
- download_link config option --> I agree on the point for the removal of `download_link` option completely and suggest to enable the pdf icon into the header by default. 
- custom theme --> IMHO a new option for this would be a sensible option. of course it has to be an optional choice for the users to chose , keeping `material` theme as default.


In the end , this is how i expect the config of plugin should look like -

mkdocs.yml -

```yaml
theme:
  name: 'my-custom-docs-theme'
  palette:
    - scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - page.toc
    - content.code.copy 
    - navigation.tabs
    - navigation.tabs.sticky 
   .
   .
   .
```  

mkdocs-pdf.yml -

```
plugins:
  to-pdf:
    enabled_if_env: ENABLE_PDF_EXPORT
    output_path: !ENV [PDF_OUTPUT_PATH, 'pdf/pdf_output.pdf']
    custom_template_path: 'pdf-templates'
    custom_mkdocs_theme: 'my-custom-docs-theme' or $theme.name                               ##optional
```

**Comment by nihalshah-dev** [comment]
@domWalters sorry if it's too much to ask for . May i know when do you plan to release the new version 0.11.0??

**Comment by domWalters** [comment]
I was kinda holding out for more content before pushing a new version.

---

However, Merry Christmas!

https://github.com/domWalters/mkdocs-to-pdf/tree/v0.10.1

https://pypi.org/project/mkdocs-to-pdf/0.10.1/

---

This has the dependencies change in it, feels like that's worthy of pushing a version.

I've been horrifically busy recently, but I intend to review #67 tomorrow, at which point I could push a `v0.11.0`, although I'd like to get more stuff in tbh.

I will not be able to do anything on this repo over the weekend unfortunately.

**Comment by woile** [comment]
I have a custom `mkdocs` theme and I still have this issue. Using version `0.10.1`. In the docs I couldn't find any information as whether my theme should be modified or not. How could I fix? 🙏🏻

**Comment by Thiti517** [comment]
Hello @woile,

This behavior occurs because the generic function used when the theme **is not Material for MkDocs** does not add any visible elements to the page. Instead, it only adds a `<link>` tag to the `<head>`.

You can verify this by inspecting the page's `HTML` structure. While some browsers or extensions can detect and display these "*alternate*" formats (like a PDF version of the page), most standard browsers do not show a visual indicator for head alternate links.

```html
<html>
  <head>
    [...]
    <link href="pdf/document.pdf" rel="alternate" title="PDF" type="application/pdf">
  </head>
```

In addition to that it seem this feature still does not work with any themes other than Material for MkDocs and default MkDocs. Therefor i strongly advise you to not use this features and simply create a page with a link to the PDF document.
